# Generated by Django 6.0.4 on 2026-04-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('calm', 'спокойный'), ('active', 'активный'), ('kid_friendly', 'для детей'), ('guide', 'поводырь')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preferred_tag',
        ),
        migrations.AddField(
            model_name='preference',
            name='preferred_tags',
            field=models.ManyToManyField(blank=True, to='accounts.tag'),
        ),
    ]
