# Generated by Django 6.0.4 on 2026-04-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
        migrations.AddField(
            model_name='animal',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
